version: '3.7'
services:
  cod4:
    image: qmcgaw/cod4
    container_name: cod4
    volumes:
      - ./main:/home/user/cod4/main
      - ./zone:/home/user/cod4/zone:ro
      - ./mods:/home/user/cod4/mods
      - ./usermaps:/home/user/cod4/usermaps:ro
      - ./logs:/home/user/.callofduty4
    network_mode: bridge
    ports:
      - 28960:28960/udp
    command: +set dedicated 2+set sv_cheats 1+set sv_maxclients 64+set ui_maxclients 64+exec server.cfg+map_rotate
    restart: always
  # =>>> http server to server mods and usermaps
  #http:
  #  image: httpd:alpine
  #  container_name: cod4-http
  #  volumes:
  #    - ./mods:/usr/local/apache2/htdocs/mods:ro
  #    - ./usermaps:/usr/local/apache2/htdocs/usermaps:ro
  #  ports:
  #    - 8000:80
  #  network_mode: bridge
  #  restart: always